name: Add Release Label

on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - synchronize
    branches:
      - release


jobs:
  release-label:
    name: Add Release Label
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - uses: actions/github-script@v6
      id: my-script
      env:
          PR_NUMBER: '${{ github.event.pull_request.number }}'
      with:
        github-token: ${{ secrets.BOT_TOKEN }}
        script: |
          const { PR_NUMBER } = process.env
          const release_label = '⚠ Release'
          await github.rest.issues.addLabels({
            issue_number: PR_NUMBER,
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: labels
          })